name: Test CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cypress
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e:ui
